# Generated by Django 4.2.30 on 2026-09-15 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0005_alter_employee_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securityrule',
            name='created_at',
        ),
        migrations.AddField(
            model_name='hrreport',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
